export const AppString = {
  constant: {

  },
  common: {
    enterYourCredentials: "Enter Your  Credentials",
    forgotPasswordTitle: "Forgot Password",
    userID: "User Id",
    enterNumber: "Enter Register Mobile Number",
    password: "Password",
    enterOtp: "Enter OTP",
    enterYourID: "Enter Your ID",
    enterYourNumber: "Enter Your Number",
    enterYourPassword: "Enter Your Password",
    remember: "Remember",
    forgotPassword: "Forgot Password",
    continue: "Continue",
    enterValidDetails: "Please enter valid details",
    resetPasswordTitle: "Reset New Password",
    enterNewPassword: "Enter New password",
    confirmNewPassword: "Confirm New password",
    atLeast8Characters: "• at least 8 characters",
    atLeast1UppercaseCharacter: "• at least 1 uppercase character",
    atLeast1LowercaseCharacter: "• at least 1 lowercase character",
    atLeast1NumberOrSpecialCharacter: "• at least 1 number or special character",
    newPasswordMustContain: "New Password Must Contain",
    passwordChangeSucessfully: "Your password has been successfully saved. Please log in with your new password.",
    OwnerName: "Owner Name",
    name: "Name",
    firstPartOfOtpDesc: "OTP has been sent to your mobile",
    secondPartOfOtpDesc: "It is valid for 5 minute ",
    thirdPartOfOtpDesc: "You can resend once the timer expires",
    submit: "Submit",
    cancel: "Cancel",
    insert: "Insert",
    delete: "Delete",
    insertTable: "Insert Table",
    edit: "Edit",
    insertLink: "Insert Link",
    selectFont: "Select Font",
    createNewStory: "Create New Story",
    viewMyAssignments: "View My Assignments",
    pushNotification: "Push Notification",
    pushNotificationDesc: "Receive updates and alerts from the app",
    changePassword: "Change Password",
    viewProfile: "View Profile",
    changePasswordDesc: "Manage or change profile password",
    DeleteAccount: "Delete Account",
    deleteAccountDesc: "Your profile, data, and history will be completely erased and cannot be recovered.",
    logOut: "Log out",
    logoutDesc: "Sign out from your account",
    WhatsApp: "WhatsApp",
    editProfile: "Edit Profile",
    mobileNumber: "Mobile Number",
    Newpasswordcannotbesameasoldpassword: "New password cannot be same as old password",
    OldPassword: "Old Password",
    EnterOldPassword: "Enter Old Password",
    NewPassword: "New Password",
    ConfirmPassword: "Confirm Password",
    EnterConfirmPassword: "Enter Confirm Password",
    Save: "Save",
    deadline: "Deadline",
    assignedBy: "Assigned By",
    accept: "Accept",
    submitStory: "Submit Story",
    seeDetails: "See Details",
    description: "Description",
    title: "Title",
    draft: "Draft",
    clear: "Clear",
  },
};
