export const AppImage = {

    home_tab_ic: require('../assets/images/home_tab_ic.png'),
    bottomnavigation_notification_ic: require('../assets/images/bottomnavigation_notification_ic.png'),
    rajexpresslogo: require('../assets/images/rajexpresslogo.png'),
    onboardingBg: require('../assets/images/onboardingBg.png'),
    gradient_line_left_to_right: require('../assets/images/gradient_line_left_to_right.png'),
    password_ic: require('../assets/images/password_ic.png'),
    user_ic: require('../assets/images/user_ic.png'),
    plus_icon: require('../assets/images/plus_icon.png'),
    plus_icon_white: require('../assets/images/plus_icon_white.png'),
    dashboard_ic: require('../assets/images/dashboard_ic.png'),
    stories_ic: require('../assets/images/stories_ic.png'),
    assignment_ic: require('../assets/images/assignment_ic.png'),
    setting_ic: require('../assets/images/setting_ic.png'),
    profile_placeholder_ic: require('../assets/images/profile_placeholder_ic.jpg'),
    setting_row_password_ic: require('../assets/images/setting_row_password_ic.png'),
    delete_user_ic: require('../assets/images/delete_user_ic.png'),
    setting_row_logout_ic: require('../assets/images/setting_row_logout_ic.png'),
    notification: require('../assets/images/notification.png'),
}